config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # get "authors", to: "authors#index"
  # get "authors/:id", to: "authors#show"

    resources :authors do
      resources :books
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

    before_action :set_author, only: [:show, :edit, :update, :destroy]

    def index
        @authors = Author.all
    end

    def show   
    end

    def new
        @author = Author.new
    end

    def create
        Author.create(params.require(:author).permit(
            :first_name, :last_name, :number_of_books, :author_birthdate))
        
            redirect_to authors_path
    end

    def edit   
    end

    def update
        @author.update(params.require(:author).permit(
            :first_name, :last_name, :number_of_books, :author_birthdate))
        
        redirect_to author_path
    end

    def destroy
        @author.destroy

        redirect_to authors_path
    end

    private

    def set_author
        @author = Author.find(params[:id])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index
        @author = Author.find(params[:author_id])
        @books = @author.books.all
    end

    def show
        @author = Author.find(params[:author_id])
        @book = @author.books(params[:id])
    end

    def new
        @author = Author.find(params[:author_id])
        @book = @author.books.new
    end

    def create
        @author = Author.find(params[:author_id])
        @author.books.create(params.require(:book).permit(
            :title, :author, :genre, :published))

        redirect_to author_books_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>

    <div class="field">
        <%= f.label :first_name, 'First Name' %>
        <%= f.text_field :first_name, placeholder: 'enter their first name' %>
    </div>

    <div class="field">
        <%= f.label :last_name, 'Last Name' %>
        <%= f.text_field :last_name %>
    </div>

    <div class="field">
        <%= f.label :number_of_books, 'Number of Books' %>
        <%= f.text_field :number_of_books %>
    </div>
    
    <div class="field">
        <%= f.label :author_birthdate, 'Birth year' %>
        <%= f.text_field :author_birthdate, placeholder: 'yyyy-mm-dd' %>
    </div>

    <%= f.submit 'Submit', :class => 'button' %>

<% end %>

app/views/authors/edit.html.erb
<%= link_to "All Authors", authors_path %>

<h1>Edit <%= @author.first_name %><%= @author.last_name %></h1>

<%= render "form" %>

app/views/authors/index.html.erb
<h1>All authors</h1>

<%= link_to "Create new author", new_author_path %>

<br></br>
<table>
    <tr>
        <th>First name</th>
        <th>Last name</th>
    </tr>

    <% @authors.each do |author| %>
        <tr>
            <td><%= link_to author.first_name, author_path(author) %></td>
            <td><%= link_to author.last_name, author_path(author) %></td>
            <td>
                <%= link_to "Edit Author", edit_author_path(author) %>
                &nbsp;|&nbsp;

                <%= link_to "Delete Author", author_path(author), 
                            data: { 
                                turbo_method: :delete, 
                                turbo_confirm: "Are you sure you want to delete #{author.first_name} #{author.last_name}?" 
                                } %>
            </td>
        </tr>
    <% end %>

</table>

app/views/authors/new.html.erb
<%= link_to "All Authors", authors_path %>

<h1>Create an author</h1>

<%= render "form" %>

app/views/authors/show.html.erb
<!--# Can two different @ not go in the same clown hat? -->
<%= link_to "All Authors", authors_path %>



<h1><%= @author.first_name %><%= @author.last_name %></h1>

<h2>Author details</h2>

<ul>
    <li>Birth year: <%= @author.author_birthdate %></li>
    <li>Number of books: <%= @author.number_of_books %></li>
</ul>


<h2>Books</h3>
<%= link_to "Show #{@author.first_name}'s books", author_books_path(@author) %>

app/views/books/index.html.erb
<h1>All books by <%= @author.first_name %> <%= @author.last_name %></h1>


<%= link_to "Back to author", author_path(@author) %>
&nbsp;|&nbsp;
<%= link_to "Add book", new_author_book_path %>

<table>
    <tr>
        <th>Title </th>
        <th>Genre</th>
        <th>Published</th>
    </tr>

    <% @books.each do |book| %>
        <tr>
            <td><%= book.title %></td>
            <td><%= book.genre %></td>
            <td><%= book.published %></td>
            
            <td>Edit book </td>
        </tr>
    <% end %>

</table>

app/views/books/new.html.erb
<%= link_to "Back to Author books", author_books_path %>

<h1>Add book by <%= @author.first_name %><%= @author.last_name %></h1>

<%= form_for [@author, @book] do |b| %>

    <div class="field">
        <%= b.label :title, 'Title' %>
        <%= b.text_field :title, placeholder: 'enter title' %>
    </div>

    <div class="field">
        <%= b.label :genre, 'Genre' %>
        <%= b.text_field :genre %>
    </div>

    <div class="field">
        <%= b.label :published, 'Year published' %>
        <%= b.text_field :published %>
    </div>

    <%= b.submit 'Submit' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>